# Generated by Django 4.1.4 on 2022-12-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodel',
            name='name',
            field=models.CharField(default='ppsu', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolmodel',
            name='start_date',
            field=models.DateField(default='2022-12-26'),
            preserve_default=False,
        ),
    ]
